# Generated by Django 3.2.3 on 2021-05-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_messages', '0006_message_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_name',
        ),
    ]
